# Generated by Django 3.0.2 on 2020-05-07 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200507_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='documents_submitted',
            field=models.CharField(blank=True, choices=[('0', 'Stamp'), ('1', 'Blank Cheque'), ('2', 'Aadhaar Card'), ('3', 'PAN Card'), ('4', 'Driving License'), ('5', 'Voter ID Card'), ('6', 'Others')], help_text='List of Submitted Documents', max_length=5, null=True, verbose_name='Documents Submitted'),
        ),
    ]
