# Generated by Django 3.0.2 on 2020-05-07 17:39

import app.model.accounts_model
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200507_2242'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='loan_created',
            field=models.DateTimeField(auto_created=True, null=True),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='image',
            field=models.ImageField(help_text='Photograph of Particular', null=True, upload_to=app.model.accounts_model.user_directory_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg'])], verbose_name='Particular Picture'),
        ),
    ]
