# Generated by Django 3.0.2 on 2020-05-09 05:11

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200507_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='loan_created',
            field=models.DateTimeField(auto_created=True, default=django.utils.timezone.now, null=True, verbose_name='Loan Creation Date'),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='loan_type',
            field=models.CharField(choices=[('DF', 'DF'), ('DS', 'DS'), ('FD', 'FD'), ('MT', 'MT'), ('RD', 'RD'), ('SM', 'SM'), ('SS', 'SS'), ('ST', 'ST')], default='DF', help_text='Loan Account Type', max_length=4, null=True, verbose_name='Loan Type'),
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txn_date', models.DateTimeField(auto_created=True, default=django.utils.timezone.now)),
                ('amount', models.FloatField(help_text='Enter received Amount', validators=[django.core.validators.DecimalValidator(10, 2)], verbose_name='Amount of Entry')),
                ('account', models.ManyToManyField(help_text='Select Account for Transaction', related_name='txn_account_relationship', to='app.Accounts', verbose_name='Account')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
            },
        ),
    ]
