# Generated by Django 3.0.2 on 2020-05-09 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20200509_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='txn_reason',
            field=models.CharField(blank=True, help_text='Remark for Transaction', max_length=512, null=True, verbose_name='Transaction Remark'),
        ),
        migrations.AddField(
            model_name='transactions',
            name='txn_type',
            field=models.CharField(choices=[('DR', 'DEBIT'), ('CR', 'CREDIT')], default='CR', help_text='Type of Transaction', max_length=5, null=True, verbose_name='Transaction Type'),
        ),
    ]
