# Generated by Django 3.0.2 on 2020-05-17 07:45

import app.model.accounts_model
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20200509_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='image',
            field=models.ImageField(blank=True, help_text='Photograph of Particular', null=True, upload_to=app.model.accounts_model.user_directory_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg'])], verbose_name='Particular Picture'),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='loan_type',
            field=models.CharField(choices=[('DF', 'DF'), ('DS', 'DS'), ('FD', 'FD'), ('MT', 'MT'), ('SM', 'SM'), ('SS', 'SS'), ('ST', 'ST')], default='DF', help_text='Loan Account Type', max_length=4, null=True, verbose_name='Loan Type'),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='account',
            field=models.ManyToManyField(help_text='Select Account for Transaction', null=True, related_name='txn_account_relationship', to='app.Accounts', verbose_name='Account'),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='amount',
            field=models.FloatField(help_text='Enter received Amount', verbose_name='Amount of Entry'),
        ),
    ]
