# Generated by Django 3.0.2 on 2020-05-17 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_balancesheet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='balancesheet',
            old_name='idd',
            new_name='DateRange',
        ),
    ]
