# Generated by Django 3.0.2 on 2020-05-18 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20200517_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='balancesheet',
            name='apk',
            field=models.BigIntegerField(null=True),
        ),
    ]
