# Generated by Django 3.0.2 on 2020-05-19 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_balancesheet_apk'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BalanceSheet',
        ),
        migrations.AddField(
            model_name='accounts',
            name='account_status',
            field=models.IntegerField(choices=[('0', 'Active'), ('1', 'Closed')], default=0, help_text='Status of Account', max_length=10, verbose_name='Status of Account'),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='txn_type',
            field=models.CharField(choices=[('DR', 'DEBIT'), ('CR', 'CREDIT'), ('PR', 'PENALTY')], default='CR', help_text='Type of Transaction', max_length=5, null=True, verbose_name='Transaction Type'),
        ),
        migrations.CreateModel(
            name='BalanceSheet',
            fields=[
            ],
            options={
                'verbose_name': 'BalanceSheet',
                'verbose_name_plural': 'BalanceSheet',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('app.transactions',),
        ),
    ]
