# Generated by Django 3.0.2 on 2020-05-19 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20200519_0851'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='loan_closed',
            field=models.DateTimeField(null=True, verbose_name='Loan Closed Date'),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='account_status',
            field=models.IntegerField(choices=[(0, 'Active'), (1, 'Closed')], default=0, help_text='Status of Account', max_length=10, verbose_name='Status of Account'),
        ),
    ]
