# Generated by Django 3.0.2 on 2020-05-19 06:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20200519_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='account_status',
            field=models.IntegerField(choices=[(0, 'Active'), (1, 'Closed')], default=0, help_text='Status of Account', verbose_name='Status of Account'),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='loan_closed',
            field=models.DateTimeField(null=True, verbose_name='Loan Closing Date'),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='loan_rate',
            field=models.FloatField(help_text='Interest Rate of Loan (in %). Applied Monthly basis.', null=True, validators=[django.core.validators.MaxValueValidator(100.0), django.core.validators.MinValueValidator(0.0)], verbose_name='Interest Rate (in %)'),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='account',
            field=models.ManyToManyField(help_text='Select Account for Transaction', related_name='txn_account_relationship', to='app.Accounts', verbose_name='Account'),
        ),
    ]
