# Generated by Django 3.0.2 on 2020-05-19 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20200519_1204'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterestTrack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest_added', models.DateTimeField()),
                ('account', models.ManyToManyField(related_name='int_account_relationship', to='app.Accounts')),
            ],
        ),
    ]
