# Generated by Django 3.0.2 on 2020-05-22 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_interesttrack'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='cash_in_hand',
            field=models.FloatField(blank=True, null=True, verbose_name='Total Profit'),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='txn_type',
            field=models.CharField(choices=[('DR', 'DEBIT'), ('CR', 'CREDIT'), ('PR', 'PENALTY'), ('IN', 'INTEREST')], default='CR', help_text='Type of Transaction', max_length=5, null=True, verbose_name='Transaction Type'),
        ),
    ]
